#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap ch &
xrandr -s 1280x800 &
pkill picom
picom &
~/.config/polybar/launch.sh
nitrogen --restore &
kitty &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 2
bspc config focus_follows_pointer true

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# counter=0
# bspc query -D --names | while read -r name; do
#   printf 'ws-icon-%i = %s;<insert-icon-here>"\n' $((counter++)) $name
# done