#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap ch &
xrandr -s 1280x800 &
pkill picom
picom &
~/.config/polybar/launch.sh
nitrogen --restore &
kitty &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.5

#bspc config normal_border_color "#777777"
#bspc config focused_border_color "#ffffff"

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#ff79c6"

#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd"